name: helloworld-go

on:
  push:
    branches: 
    - master
    paths:
    - '.github/workflows/helloworld-go.yml'
    - 'apps/helloworld/go/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout project
      uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2.0.3
      with:
        go-version: '1.14.2'
    - name: Build Go app
      working-directory: apps/helloworld/go
      run: go build myrest.go
